### ISSUE TITLE
Json parsing error

### ISSUE THREAD

**Issue by andig** [DanielHuisman/traefik-certificate-extractor#15]
I've mounted the acme folder and add an empty line to the `acme.json` to trigger certificate export. This fails with json decode error while (according to jsonlint) the json is valid:

    admin@NAS:~$ sudo docker run --rm -v /volume1/data/docker/traefik/:/app/data -v $(pwd)/certs:/app/certs danielhuisman/traefik-certificate-extractor
    Certificates changed
    Extracted certificate for: ***
    Certificates changed
    Exception in thread Thread-1:
    Traceback (most recent call last):
    File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
        self.run()
    File "/usr/local/lib/python3.7/site-packages/watchdog/observers/api.py", line 199, in run
        self.dispatch_events(self.event_queue, self.timeout)
    File "/usr/local/lib/python3.7/site-packages/watchdog/observers/api.py", line 368, in dispatch_events
        handler.dispatch(event)
    File "/usr/local/lib/python3.7/site-packages/watchdog/events.py", line 330, in dispatch
        _method_map[event_type](event)
    File "extractor.py", line 15, in on_modified
        self.handle(event)
    File "extractor.py", line 23, in handle
        data = json.loads(open(event.src_path).read())
    File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
        return _default_decoder.decode(s)
    File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by andig** [comment]
Seems solved downstream in https://github.com/SnowMB/traefik-certificate-extractor

Not sure if there is any interest in merging the downstream changes here?
